-- Atividade 1 - Lab 02 - Ana Luísa Londres - 20220060649

-- Questão:
CREATE TABLE TABELA_A (
  CODIGO INTEGER PRIMARY KEY,
  NOME TEXT NOT NULL
);

CREATE TABLE TABELA_B (
  ID SERIAL PRIMARY KEY,
  CODIGO INTEGER,
  VALOR NUMERIC(10,3)
);

INSERT INTO TABELA_A (CODIGO, NOME) VALUES
(1, 'UM'),
(2, 'DOIS'),
(3, 'TRES'),
(4, 'QUATRO'),
(5, 'CINCO');

INSERT INTO TABELA_B (CODIGO, VALOR) VALUES
(1, 1000.000),
(1, 2000.000),
(1, 5000.000),
(2, 4000.000),
(2, 9000.000),
(3, 7000.000),
(5, 4000.000),
(8, 7000.000);



-- Pesquisas com os JOIN's

-- Inner
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
INNER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;

-- Left Outer
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
LEFT OUTER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;

-- Right Outer
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
RIGHT OUTER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;

-- Full Outer
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
FULL OUTER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;